### ISSUE TITLE
Investigate failures in OIDC test when running on MacOS

### ISSUE THREAD

**Issue by kabir** [wildfly-extras/wildfly-cloud-tests#40]
[ElytronOidcClientTestCaseIT](https://github.com/wildfly-extras/wildfly-cloud-tests/blob/main/tests/elytron-oidc-client/auto-registration/src/test/java/org/wildfly/test/cloud/elytron/oidc/client/autoreg/ElytronOidcClientTestCaseIT.java) fails when trying to run it locally on MacOS (I've tried both M1 and Intel versions).

However, it passes on CI and I think for @jfdenise who is on Linux.

https://gist.github.com/kabir/9af03261382d6a33e805c2e29502a2d6#file-gistfile1-txt contains the console output, while https://gist.github.com/kabir/9af03261382d6a33e805c2e29502a2d6#file-clustering-tests contains the logs from the keycloak server which is started in [tests/elytron-oidc-client/auto-registration/src/test/container/keycloak.yml](https://github.com/wildfly-extras/wildfly-cloud-tests/blob/main/tests/elytron-oidc-client/auto-registration/src/test/container/keycloak.yml).

It seems to be complaining that UDP is not available. 

https://gist.github.com/kabir/9af03261382d6a33e805c2e29502a2d6#file-gistfile1-txt-L96-L101
```

15:12:30,968 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-2) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
15:12:31,001 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
15:12:35,977 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 56) failed setting interface to /172.17.0.5: java.net.SocketException: Protocol not available (Error setting socket option)
15:12:35,983 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 56) failed setting interface to /172.17.0.5: java.net.SocketException: Protocol not available (Error setting socket option)
15:12:35,988 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 56) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
	at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:66)
	at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
	at org.jboss.as.clustering.jgroups@26.0.1.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:116)
	at org.jboss.as.clustering.jgroups@26.0.1.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:58)
	at org.wildfly.clustering.service@26.0.1.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:63)
	... 7 more
Caused by: java.net.SocketException: Protocol not available
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:235)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UDP.createSockets(UDP.java:417)
	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UDP.start(UDP.java:292)
	at org.jgroups@4.2.15.Final//org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:881)
	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.startStack(JChannel.java:989)
	at org.jgroups@4.2.15.Final//org.jgroups.JChannel._preConnect(JChannel.java:853)
	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.connect(JChannel.java:358)
	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.connect(JChannel.java:352)
```

Assuming the server is the same on MacOS/Linux, it looks like UDP is available in the Linux variant of Minikube but not on MacOS?

**Comment by pferraro** [comment]
That test should probably be modified to update the default stack to use a pure TCP-based protocol stack (as we do for the clustering testsuite).  As to why UDP is not available in minikube on MacOS, I have no idea.  Perhaps one of the aaple fanboys on the clustering team might have more insight? CC: @rhusar

**Comment by kabir** [comment]
Actually, looking further into it, this UDP issue only happens on M1. One explanation might be that the keycloak image is AMD, while M1 expects ARM. It still fails on Intel, but the problem is something else, which I'll check tomorrow

**Comment by rhusar** [comment]
@kabir Any update on this btw?

**Comment by kabir** [comment]
Hi, yes - I've upgraded to latest Keycloak (the Quarkus based one) so this particular problem has gone away. The tests still fail on Mac, but now it is something else

**Comment by rhusar** [comment]
Great!
